### ISSUE TITLE
Data Preparation and LIME Output 

### ISSUE THREAD

**Issue by FrancaSp** [FrancaSp/DBMS__Florian_Franca#3]
Lime seems to have some problems with float data, so at the moment in out notebook all variables are converted into dummys.

Probably we should define some ranges for the variables: "PayRate" and "EngagementSurvey"

**Comment by schauerflorian** [comment]
Thanks for sharing! 

For PayRate I guess we could just use force the float into an int, because often the values are xx.00 and in the broad range .5 more or less does not really matter??
For EngagementSurvey it seems more complicated, but again all I can think of is coercion
